[tool.poetry]
name = "curriculum-deeplab"
version = "0.1.0"
description = ""
authors = ["Christian Weihsbach <christian.weihsbach@uni-luebeck.de>"]
readme = "README.md"
packages = [{include = "curriculum_deeplab"}]

[tool.poetry.dependencies]
python = "^3.9"
meidic-vtach-utils = {git = "git@github.com:MDL-UzL/meidic_vtach_utils.git", rev = "main"}
torch = "^1.9.1"
torchvision = "^0.10.1"
connected-components-3d = "^3.3.0"
mdl-seg-class = {git = "git@github.com:MDL-UzL/SegmentationClassification.git", rev = "main"}
nibabel = "^3.2.1"
scipy = "^1.6.0"
scikit-image = "^0.18.3"
tqdm = "^4.62.2"
wandb = "^0.12.2"
jupyterlab = "^3.2.0"
ipywidgets = "^7.6.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
